train:
  _target_: src.datasets.MeladzeDataset
  images_dir_path: /home/aamatosyan/pers-diffusion/OurPhotoMaker/meladze_set/images
  captions_path: /home/aamatosyan/pers-diffusion/OurPhotoMaker/meladze_set/meladze_gemini_captions.txt
  instance_transforms: ${transforms.instance_transforms.train}
