compute_environment: LOCAL_MACHINE
distributed_type: NO
# mixed_precision: 
main_process_port: 29503
use_cpu: false
num_processes: 1
num_machines: 1
gpu_ids: "all"
rdzv_backend: static
machine_rank: 0
main_training_function: main