device: "auto"
train: []
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.IDSim
    name: "id_sim" # it is better to avoid spaces in names
  - _target_: src.metrics.TextSimMetric
    name: "text_sim"