train:
    _target_: torch.utils.data.DataLoader
    batch_size: 2
    num_workers: 1
    pin_memory: False

val:
    _target_: torch.utils.data.DataLoader
    batch_size: 1
    num_workers: 1
    pin_memory: False

ood_val:
    _target_: torch.utils.data.DataLoader
    batch_size: 1
    num_workers: 1
    pin_memory: False
