train:
  pixel_values: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.Resize
        size: [512, 512]
        interpolation: 2
      - _target_:  torchvision.transforms.ToTensor
      - _target_:  torchvision.transforms.Normalize
        mean: [0.5]
        std: [0.5]

inference: null
